# Generated by Django 4.2.1 on 2023-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurgaTemp_Calculator', '0002_alter_history_converted_alter_history_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
